quarkus.application.name=chat-demo

casehub.chat.backend.path=chat-demo.db
casehub.chat.backend.seed=demo-seed.db

quarkus.http.port=8090

quarkus.quinoa.build-dir=dist
quarkus.quinoa.package-manager-install=true
quarkus.quinoa.package-manager-install.node-version=22.16.0
quarkus.quinoa.enable-spa-routing=true
